### ISSUE TITLE
issues when adding compile 'com.firebaseui:firebase-ui-auth:1.0.1'

### ISSUE THREAD

**Issue by engr-erum** [udacity/and-nd-firebase#4] opened 2016-12-13 12:57 UTC
i am using AS-2.1.2 everything is ok but when adding this compile 'com.firebaseui:firebase-ui-auth:1.0.1' i m getting error 

Error:Failed to resolve: com.android.support:support-v4:25.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:D:/AndroidProjects/ChatApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

can someone pls help me what's the issue ?

**Comment by danielmai** [comment] 2016-12-21 23:50
Duplicate of issue #3. Let's continue the conversation there.

**Closed as completed by danielmai** 2016-12-21 23:50 UTC
